### ISSUE TITLE
Profiling of project service methods

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#157]
Specifically, need to profile time consumed in phases/products/timelines/milestones endpoints. It would be great if we can also track the memory as well consumed in these endpoints.

**Comment by ngoctay** [comment]
@gondzo 
I understood that "profile time consumed" means adding logs (using winston, for example) for all endpoints. Is that correct?

**Comment by vikasrohit** [comment]
Yes that is one part. However, mainly we need the data about the time/memory consumed as a report or an easy way to get that report from dev environment. We need to identify if there is possibility of improving the performance because we are facing slow responses in some cases.

**Comment by vikasrohit** [comment]
One more thing, this is on least priority right now in the tasks. We can tackle this in last.

**Comment by ngoctay** [comment]
1. Currently we already log the `duration` of each request. So it's unnecessary to add `winston`.
2. For memory, I will use memwatch (https://www.npmjs.com/package/memwatch-next) to detect and log the memory leaks

**Comment by vikasrohit** [comment]
Okay, great!! Can you please compile a simple report which states every route and its time/memory consumed?

**Comment by ngoctay** [comment]
@vikasrohit 
A report in Excel, OK?
This will take quite a lot of time, so I will do this in last.

**Comment by vikasrohit** [comment]
Yes, excel would be good for now. And yes, it is the last priority.

**Comment by ngoctay** [comment]
Please check the report.

- `POST /projects` and `PATCH /projects` take more than 1s
- I don't see any memory leak
- I don't test metadata endpoints because they are very simple

| Request | Route                                                                   | Duration (ms) | Heap Used (B) |
|---------|-------------------------------------------------------------------------|---------------|---------------|
| POST    | /projects                                                               | 5170.655399   | 65363392      |
| GET     | /projects                                                               | 63.2839       | 66343688      |
| GET     | /projects/:projectId(\d+)                                               | 25.1262       | 66520648      |
| PATCH   | /projects/:projectId(\d+)                                               | 1098.612201   | 69384672      |
| DELETE  | /projects/:projectId(\d+)                                               | 41.0858       | 69589968      |
| POST    | /projects/:projectId(\d+)/members                                       | 22.4345       | 69569904      |
| DELETE  | /projects/:projectId(\d+)/members/:id(\d+)                              | 45.2879       | 69951624      |
| PATCH   | /projects/:projectId(\d+)/members/:id(\d+)                              | 46.988399     | 71140424      |
| POST    | /projects/:projectId(\d+)/attachments                                   | 25.8274       | 71619280      |
| GET     | /projects/:projectId(\d+)/attachments/:id(\d+)                          | 935.1773      | 67770176      |
| PATCH   | /projects/:projectId(\d+)/attachments/:id(\d+)                          | 31.4825       | 71701048      |
| DELETE  | /projects/:projectId(\d+)/attachments/:id(\d+)                          | 33.4117       | 67864128      |
| POST    | /projects/:projectId(\d+)/upgrade                                       | 37.360599     | 68339112      |
| GET     | /projects/:projectId(\d+)/phases                                        | 9.616099      | 69286816      |
| POST    | /projects/:projectId(\d+)/phases                                        | 53.760001     | 69884704      |
| GET     | /projects/:projectId(\d+)/phases/:phaseId(\d+)                          | 11.692501     | 69824064      |
| PATCH   | /projects/:projectId(\d+)/phases/:phaseId(\d+)                          | 46.9699       | 70794128      |
| DELETE  | /projects/:projectId(\d+)/phases/:phaseId(\d+)                          | 34.4258       | 71699240      |
| GET     | /projects/:projectId(\d+)/phases/:phaseId(\d+)/products                 | 13.0936       | 71402080      |
| POST    | /projects/:projectId(\d+)/phases/:phaseId(\d+)/products                 | 55.129301     | 72445648      |
| GET     | /projects/:projectId(\d+)/phases/:phaseId(\d+)/products/:productId(\d+) | 8.594301      | 72714336      |
| PATCH   | /projects/:projectId(\d+)/phases/:phaseId(\d+)/products/:productId(\d+) | 36.291801     | 72719896      |
| DELETE  | /projects/:projectId(\d+)/phases/:phaseId(\d+)/products/:productId(\d+) | 41.5369       | 73514864      |
| POST    | /timelines                                                              | 31.8519       | 73913360      |
| GET     | /timelines                                                              | 64.7114       | 74079520      |
| GET     | /timelines/:timelineId(\d+)                                             | 23.7114       | 74132440      |
| PATCH   | /timelines/:timelineId(\d+)                                             | 55.1774       | 75349192      |
| DELETE  | /timelines/:timelineId(\d+)                                             | 44.769899     | 75647808      |
| POST    | /timelines/:timelineId(\d+)/milestones                                  | 41.951501     | 67656992      |
| GET     | /timelines/:timelineId(\d+)/milestones                                  | 15.737399     | 68176304      |
| GET     | /timelines/:timelineId(\d+)/milestones/:milestoneId(\d+)                | 19.777        | 68146072      |
| PATCH   | /timelines/:timelineId(\d+)/milestones/:milestoneId(\d+)                | 64.3966       | 68949304      |
| DELETE  | /timelines/:timelineId(\d+)/milestones/:milestoneId(\d+)                | 33.704499     | 71296528      |

**Comment by vikasrohit** [comment]
Closing as working fine as per given requirements.

@gondzo Please feel free to tag it as per convenience for payment.
