### ISSUE TITLE
Cannot change project status

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#366]
When I'm trying to change project status from `active` to `draft` I'm getting the error `["Scope changes are not allowed for 'active' project"]`.

Request:

![image](https://user-images.githubusercontent.com/146016/63143598-ac60f580-c021-11e9-8ecb-24acc358e66a.png)

Response:

![image](https://user-images.githubusercontent.com/146016/63143623-d0bcd200-c021-11e9-9493-67e9206e4e14.png)

If it's not allowed to change project status from `active` I think we should update the error message accordingly.

If it's allowed to change project status from `active`, then we should fix it, and only don't let to change the scope of active projects, but let changing other things like `status`.

**Comment by vikasrohit** [comment]
Good catch @maxceem. As of now, we don't have any constraint on project status movement except moving from a completed or cancelled project and don't letting activation of project without having at least one phase in review status. Also, the logic I placed for scope changes validation, should allow all project fields to be updated which are not listed in `scopeChangeFields` property of the template used in the project. I am also able to reproduce the issue even if the `scopeChangeFields` does not have `status` field listed. So, it seems a bug.
Can you please get it fixed either via private task or next bug bash? I would like get some unit tests added for this as well because I missed to get unit tests added in project's update route when implemented the scope change workflow.

**Comment by vikasrohit** [comment]
This can be closed @maxceem I think because the original issue was appearing because of scope change request changes which right now are disabled.

**Comment by maxceem** [comment]
Yes, closing it as I cannot reproduce it anymore.
