### ISSUE TITLE
Metadata update is not updating ES index

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#428]
@maxceem fyi

**Comment by maxceem** [comment]
The first fix has been applied via https://github.com/topcoder-platform/tc-project-service/pull/430/commits/f55da524c5b288bd4bac797e5be88e8fe0afac0f and https://github.com/topcoder-platform/tc-project-service/pull/430/commits/992208d04c14dd93bb3e377e20f1db582b52c4c4 but looks like it doesn't work on PROD even though it works Locally.

Have to debug it at DEV or PROD.

**Comment by maxceem** [comment]
The issue was because in `project-processor-es` we explicitly define the id of doc which would contain all the metadata. And in the script to index metadata from DB to ES we didn't define the id explicitly, so the random id was generated. This lead do the fact, that if we change metadata at least once `project-processor-es` index the change and put into a different ES document from what we had when we initially indexed data from DB to ES. But when we get data via endpoints we still got it from the first document, created by indexing script.

This has been fixed in the next commit https://github.com/topcoder-platform/tc-project-service/commit/b159fb5d5260e03d3df23d852f2eb02826c45c0e
 and pushed to DEV.

It has been tested on DEV and works well now.

To apply the fix on PROD, metadata index should be recreated using admin endpoints:
- delete metadata index
- create metadata index
- index metadata from DB to ES

**Comment by vikasrohit** [comment]
Good catch @maxceem. Working fine for me. @RishiRajSahu please verify if it works for you as well.

**Comment by maxceem** [comment]
@vikasrohit this fix hasn't been yet applied to PROD, only to DEV. Would you like me to create a HOTFIX for PROD?

**Comment by vikasrohit** [comment]
Nopes, we should be good with our regular release update to production.
