### ISSUE TITLE
Copilot not added to direct project when joining

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#524]
Copilots are not currently added to the direct project when joining through invite. Can this be automated (it was a feature at some point in the past if I remember correctly?)

**Comment by vikasrohit** [comment]
It should be still there, I mean we are listening the member addition event which is still raised after the copilot accepts the invite. So, ideally, copilot should have been added to the team. If it is not, I guess, something is broken.

**Comment by maxceem** [comment]
@vikasrohit I've just joined as a copilot to a new project https://connect.topcoder.com/projects/14269 but I wasn't added to the direct project. Looks like there is some issue in https://github.com/topcoder-platform/legacy-project-processor.

**Comment by vikasrohit** [comment]
ohk, can we get it fixed in this release? I guess, it would be important considering that we are trying to move one of api callers to use v5 apis to add members to the direct project (via legacy processsor).

**Comment by maxceem** [comment]
@vikasrohit I think I've got where the issue comes from, though I'm not sure what the desired solution should be. Also, there are more cases that fails when members are added or join.

For example another issue:
- I use account `max.admin` with `administrator` privileges, and join a project https://connect.topcoder-dev.com/projects/9145 as a `Manager`. But after joining as a manager, I still cannot see the corresponding Direct project https://www.topcoder-dev.com/direct/projectOverview.action?formData.projectId=22743.

The reason for this is how the Legacy Project Processor checks permissions.
Before adding a manager or copilot member Legacy Processor check, that the user WHO adds a member has full permission to manage Direct project https://github.com/topcoder-platform/legacy-project-processor/blob/develop/src/services/ProcessorService.js#L881-L887.

And as per the logic here, the user may only has full permissions to manage Direct project if such a user is **already a project member** with manager role or account manager role.

- So in all the cases when user is not yet a member a project and he tries adding a manager or copilot, it would fail.
- Also, is a manager joins a project by himself, it would also fail because he would be the user who adds himself, but as he is not a member of the project, so he cannot add himself to the direct project.

### Possible solutions

1. Remove permissions check form Legacy Processor before adding a new member (manager or copilot) as basically it's code duplication. The permission to added a member have been already checked in Project Service. And nobody can send Kafka message to Legacy Processor directly. So if Legacy Processor got the even to add member the legacy processor can just do it. 
    - For example, our another processor Project ES Processor just gets Kafka message with any objects and indexes without checking any permissions again.

2. Otherwise, I guess we have to add the logic to Legacy Projects processor to not only check project member permissions, but also check Topcoder Roles which has permissions to add themself directly, or other users without joining the project. Though it would mean we would duplicate this logic from Project Service.

**Comment by vikasrohit** [comment]
@maxceem first things first. I think when the legacy processor was developed, we (you and me) were not in loop so I have no idea what was the intent there. However, because I was involved in code changes earlier where we used to call the direct api to add users to the direct project, I think it is more of permissions checks needed by direct and I guess the original copilot and developers jsut replicated the same permissions checks as they are in direct api. Further, the direct api used to ask for a user id who is authorized to do those operations which requirement was removed last year by https://github.com/appirio-tech/tc-direct-project-service/commit/39258bf4273a304f692c4eb17dd4e24222482197. Now direct api picks the user id from env variable. So, that means it always need an authorized user's id to perform that operation. I am not sure how they are using that user to authorize for the calls, but I think even though it is using that single user to authorize all m2m calls, it makes the api accessible to everyone who has the relevant scopes.
So, I think the #1 should be good for us considering that we are going to get rid of direct projects and connect projects as primary source of grouping the challenges. So, I think it is safe to process member addition requests to direct project assuming that whoever has sent the event to bus, has already did the permissions checks.

**Comment by maxceem** [comment]
@vikasrohit this is fixed now on DEV via https://github.com/topcoder-platform/legacy-project-processor/commit/d7aa00be9371c5408b622a948802d0b4fda727a6.

Let me know if the fix looks good to you and we can open this issue for QA.

**Comment by maxceem** [comment]
## QA guidelines

### Copilot add / remove

- Using any `Connect Manager` user invite `Connect Copilot` user
- Using admin `Connect Copilot Manager` user accept copilot user invite
- Login using Copilot User and click link **Project in Topcoder Direct** 

   ![image](https://user-images.githubusercontent.com/146016/80088579-61f72780-8565-11ea-98f7-17c4f7b00bd6.png)

    - you should get access to the Direct project

- Now using admin `Connect Copilot Manager` user accept copilot user invite, remove Copilot User form the project (in Connect)

- Reload the Direct project by Copilot User, you shouldn't have access now

### Manager join / leave

- Using any user with `Connect Manager` or `Connect Account Manager` role who is NOT a project member, join project as a `Manager` or `Account Manager`

- Now link **Project in Topcoder Direct** 

   ![image](https://user-images.githubusercontent.com/146016/80088579-61f72780-8565-11ea-98f7-17c4f7b00bd6.png)

    - you should get access to the Direct project

- And now **leave** project on Connect. And reload Direct project page, you shouldn't have access now.

**Comment by vikasrohit** [comment]
Looks good to me.

**Comment by codejamtc** [comment]
@maxceem 

- Login using Copilot User and click link Project in Topcoder Direct > you should get access to the Direct project. ❌ Failed

https://monosnap.com/file/p06oXjRN5hjmXmAJArdHz11Lpsxcxo

**Comment by codejamtc** [comment]
@maxceem Checked using the same operation with `pshah_copilot` 

- Login using Copilot User and click link Project in Topcoder Direct > you should get access to the Direct project. 🆗 Pass

https://monosnap.com/file/GdzcmrOdKRr2vrD4aazv89m11ypxld

**Comment by maxceem** [comment]
@vikasrohit find out about one more nuance:

To be able to add a copilot to the Direct the copilot user should be somehow additionally marked as a "copilot":
```sql
select copilot_profile_id from tcs_catalog:copilot_profile where user_id = ${userId} and copilot_profile_status_id = 1
```

So the fix works for `pshah_copilot` (which probably has that flag) but doesn't work for 2 other copilots we tried it with:
- **TCConnCopilot** -  copilot with only `Connect Copilot` role
- **copilot_codejam** - copilot with `Connect Copilot` and `copilot` roles is not enough.

I think this additional check probably is not an issue, and all real copilots would pass it.
Please, let me know if this additional check is desired, or we should also remove it?

**Comment by vikasrohit** [comment]
Yep, agreed. Leave that additional check as is because real copilots on production has that profile. It is part of the copilot on boarding, I guess.

**Comment by maxceem** [comment]
@codejamtc as per Vikas clarification https://github.com/topcoder-platform/tc-project-service/issues/524#issuecomment-618922612 we only have to support this feature for "real" copilot user as `pshah_copilot`.

So I guess we can proceed with the second part of testing **Manager join / leave**: https://github.com/topcoder-platform/tc-project-service/issues/524#issuecomment-618322209.

**Comment by maxceem** [comment]
Some helpful information I've been using during debugging this issue in case we have any issues in the future:
- This functionality has been implemented in the challenge **Topcoder Project API - Legacy Project Processor - Part 2** https://www.topcoder.com/challenges/30098153?tab=details. The winner is [icemanzzz](https://www.topcoder.com/members/icemanzzz)
- Commit of this functionality implementation https://github.com/topcoder-platform/legacy-project-processor/commit/2878e2e58a69c9ad5b062468322bd8db5486156d

**Comment by codejamtc** [comment]
@maxceem According to the test performed here https://github.com/topcoder-platform/tc-project-service/issues/524#issuecomment-618457741

Checked with `pshah_copilot` 

- Login using Copilot User and click link Project in Topcoder Direct > you should get access to the Direct project. 🆗 Pass

https://monosnap.com/file/GdzcmrOdKRr2vrD4aazv89m11ypxld

Checked with `pshah_manager` 

- Login using Manager User and join to a Project > you should get access to the Direct project. Leave the project and you can't access the direct link anymore. 🆗 Pass

https://monosnap.com/file/XvvETZZxhOYadvHP0iPQvcPENL98FF

**Comment by vikasrohit** [comment]
Closing. @codejamtc please feel free to reopen if you find it not working in production.
