### ISSUE TITLE
Get rid of consuming events from RabbitMQ

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#584]
Currently we might be using few RabbitMQ event to complete some of the use cases and features in project service. There was one major part which was dependent on the RabbitMQ events and it was tc-connect2sf which is recently moved away from RabbitMQ to Kafka, so we have to start working on moving all the logic which is still using RabbitMQ, to use Kafka instead.

fyi @maxceem as we discussed.

**Comment by maxceem** [comment]
I've noticed one side effect after moving the processing `phase created` event from RabbitMQ to Kafka.
When we add a new phase in Connect, we reload the list of phases immediately after that. Phases are reloaded from ES so at the time we reload phases it often happens that the newly added phase is not yet indexed to ES so we cannot see a newly added phase.

It seems that RabbitMQ processed the events faster so this issue didn't happen before. Note, that we index phases inside Project Service for now because of cascading updates, so before indexing was handled by RabbitMQ event, and now by Kafka event.

![image](https://user-images.githubusercontent.com/146016/96123292-4a3ca280-0efb-11eb-84ed-28aa774cc199.png)

I would think what would be the best solution here, for now just let you know.

**Comment by vikasrohit** [comment]
Good observations @maxceem and good to know that fact that RabbitMQ was faster then Kafka at least for our use case. And I think one important reason of delay in kafka based processing is that we are using REST API endpoint to post a message to bus which definitely causes full HTTP request cycle latency before actual message reaches to the Kafka server. I am not sure if after reaching kafka server, message is delayed further or not.
May be, we can add false loading of 5 seconds or so, just like we did for invite accept in Connect.

> that we index phases inside Project Service for now because of cascading updates

Just for reference, can you please mention what type of cascading we are doing with phases? I mean I remember cascading for milestones because we don't allow setting of their start dates and we were controlling the start-end dates of milestones automatically. But I am unable to recall why what cascading updates we need for phases.

**Comment by maxceem** [comment]
@vikasrohit 

1. > Just for reference, can you please mention what type of cascading we are doing with phases? I mean I remember cascading for milestones because we don't allow setting of their start dates and we were controlling the start-end dates of milestones automatically. But I am unable to recall why what cascading updates we need for phases.

   We do cascade updates for the `order` field, see:
   - `add` https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/phases/create.js#L76-L92
   - `update` https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/phases/update.js#L89-L151

   Though I can see that we never use `order` in Connect App and more than that in real data we never define it at all:

   ![image](https://user-images.githubusercontent.com/146016/96248383-2b4e1700-0fb4-11eb-81d1-a848b5930074.png)

   So I would suggest removing this logic from the backend.

2. As we don't really use cascade updates, so to solve this issue in Connect App we can just add the newly created phase client-side without reloading all the phases.

**Comment by maxceem** [comment]
This is done via 3 PRs:
- **Project Service** https://github.com/topcoder-platform/tc-project-service/pull/585
   - move actual handles from RabbitMQ to Kafka
   - removed unused RabbitMQ handles code
   - removed all RabbitMQ events firing
   - added support for graceful shutdown of index-kafka.js (otherwise it may bring issues even in production, as badly stopped service might still listen to events in the background and cause issue like `versions conflict` during ES indexing)
   - removed RabbitMQ from production and local deployment
   - fix unit tests to use a single ES service which refreshes data after updating
   - removed redundant seedElasticsearchIndex.js script (we have a new one "npm run data:import")
- **Connect App** https://github.com/appirio-tech/connect-app/pull/4155
   - fix for the issue during phases adding described [above](https://github.com/topcoder-platform/tc-project-service/issues/584#issuecomment-709286420) - we don't reload phases and just add a new phase client-side
- **Project ES Processor** https://github.com/topcoder-platform/project-processor-es/pull/50
   - **Project Service** doesn't handle phases reindexing anymore, so this is enabled in **Project ES Processor**

**Comment by vikasrohit** [comment]
> So I would suggest removing this logic from the backend.

@maxceem the PR has this logic removed now, right?

**Comment by maxceem** [comment]
> @maxceem the PR has this logic removed now, right?

No, I didn't remove it without the confirmation. But I can do that.

**Comment by vikasrohit** [comment]
okay. Does that mean the PR is still updating the `order` field?

**Comment by maxceem** [comment]
Yes, potentially it can update `order`, but in reality, it never happens, because we never set `order`. To trigger the cascading logic we have to set `order` first.

**Comment by vikasrohit** [comment]
okay, please remove the logic for handling order as we are not using it as of now and it is causing more problems than future features.

**Comment by maxceem** [comment]
@vikasrohit removed phase order cascading updates and added one more commit https://github.com/topcoder-platform/tc-project-service/pull/585/commits/c5a01ed880a5037039e6bfb1c34baabe202d2aff to the PR.

**Comment by vikasrohit** [comment]
@maxceem I have merged all 3 PRs and asked your input on https://github.com/appirio-tech/connect-app/issues/4172

**Comment by maxceem** [comment]
@vikasrohit I've added QA guidelines there.

**Comment by maxceem** [comment]
@vikasrohit this is done and has been working good for some time, so we can close it.
