### ISSUE TITLE
Searching projects with space does't sort results in expected way

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#645]
We come across this issue when using Projects API in TaaS App https://github.com/topcoder-platform/taas-app/issues/37#issuecomment-755873866

But it can be also reproduced in Connect App:
- what I'm expecting is to have projects which has both words in `name`, `description` or user name on top
- but instead, I'm getting a mix of results with only one of these words present

![image](https://user-images.githubusercontent.com/146016/111283410-c3295d00-8647-11eb-9af7-1b58a713e1b6.png)

One more example:
- `taas` returns a lot of projects with `test taas` words https://connect.topcoder-dev.com/projects?keyword=taas&sort=updatedAt%20desc:

   ![image](https://user-images.githubusercontent.com/146016/111284216-99bd0100-8648-11eb-817f-8d4998a5135e.png)

- but if we search `test taas` we would not get them https://connect.topcoder-dev.com/projects?keyword=test%20taas&sort=updatedAt%20desc:

   ![image](https://user-images.githubusercontent.com/146016/111284303-ae999480-8648-11eb-8e55-8480f0e7ff89.png)
   
- when searching by `test taas` I would expect found projects with the direct order of word `test taas` to be on the top. And they could be followed projects with reverse order `taas test` or mixed pharses like `test [other words] taas` and `taas [other words] test`.

Here is the code which builds the search requests to the ES https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/projects/list.js#L73

**Comment by vikasrohit** [comment]
@maxceem I don't think it is easy to achieve what we are required here because it might mess up the existing working searches for users. Do you think we have any good solution for this in ES?

However, I do know that we can force the combination of words to be searched in order and in fact it is already supported. https://connect.topcoder-dev.com/projects?keyword=%22test%20taas%22&sort=updatedAt%20desc You have to pass the keywords in quotes and you can force them in order. however it won't search the reverse order by default and that is what I am concerned above when I said `it is not easy without effecting existing queries`.
Personally, I never need such generic search because it most of the time confuses with results and it is always better to have predictable results. In your examples above `test taas` returns projects which have any of these keywords, however, because `test` is present in many of projects, you don't see the `taas` projects in first page.

**Comment by maxceem** [comment]
I agree that it's most likely not easy to achieve. The reason why I logged this issue is that during the QA of the TaaS App such behavior of Projects API was not expected by the QA team https://github.com/topcoder-platform/taas-app/issues/37#issuecomment-755873866:

![image](https://user-images.githubusercontent.com/146016/111300116-646cdf00-8659-11eb-94d3-ae1978ef3b1c.png)

So I logged it in case we could find a better approach. 
At the moment the team of the Topcoder Challenge API is working on improving the search feature there. Maybe we can wait for them, and see what results they could achieve there and see if we could incorporate similar improvements in Projects API after.

**Comment by vikasrohit** [comment]
Would quoting the user enter text automatically won't work for you @maxceem ? I mean when user enters `TAAS PROJECT SAAR` you pass `"TAAS PROJECT SAAR"`?

**Comment by maxceem** [comment]
Great suggestion @vikasrohit I would update the logic to use quotes during searching and would ask QA team for the feedback if they see any drawback of such an approach.

**Comment by maxceem** [comment]
@vikasrohit the way you suggested with "" works good for the QA team. So I guess we can close this issue for now.
