### ISSUE TITLE
Update project creation endpoint to create phases and products based on project template specified in the payload

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#86]
We have to create default phases and products as per the specified project template id in the project creation endpoint. Following are the key points:

1. Update `POST /v4/projects` endpoint to create phases and products as per the template specified in POST body as `projectTemplateId` param. Store the project template id in a new field(`projectTemplateId`) in the project table.
2. Project templates are stored in `project_templates` table represented by ProjectTemplate model.
3. Each project template contains a json field `phases` which contains array of objects and each object represents a phase. Each phase object has default values for few fields and a products array. Products array contains objects which represent default values for some of the fields of a product and more importantly the id of the product. We use this product id to create a new product.
Sample phases field value:
```javascript
[{
  name: "Design Stage",
  products: [
    {
      id: 21,
      productKey: 'visual_design_prod'
    }
  ]
}, {
  name: "Development Stage",
  products: [
    {
      id: 23,
      productKey: 'website_development'
    }
  ]
}]
```
4. Project, Phase and Product should be stored in database in a single database transaction.

**Comment by ngoctay** [comment]
@vikasrohit @coderReview 
Currently `phases` is an object, not array of objects.
I can change it to accept both object and array of objects.
However, in PATCH /projectTemplates/{templateId}, we need to merge this JSON field.
If `phases` is an array, there's no way to merge it: we don't know that we need to replace an existing array item or add a new items. We also can't remove a phase from the array.

***Suggestion***: instead of using an array, we can use an object like this:

```
{
  items:[
    {
      name:"Design Stage",
      products:[
        {
          id:21,
          productKey:'visual_design_prod'
        }
      ]
    },
    {
      name:"Development Stage",
      products:[
        {
          id:23,
          productKey:'website_development'
        }
      ]
    }
  ]
}
```

**Comment by coderReview** [comment]
@ngoctay why is there any issue using array with patch? following previous requirements array is always replaced by new array during PATCH operation.

**Comment by vikasrohit** [comment]
I am okay with suggested structure as well, as it just moves the actual
phases array in a field of the parent object. We kept phases as object so
that we can add more info in future to the object.


Paulo, we just need to make sure that our upgrade(migration) endpoint also
uses the phases object in same way. Btw, does the dev-challenges branch
contains the migration challenge output?

On May 31, 2018 7:04 AM, "Paulo Vitor Magacho" <notifications@github.com>
wrote:

@ngoctay <https://github.com/ngoctay> why is there any issue using array
with patch? following previous requirements array is always replaced by new
array during PATCH operation.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/topcoder-platform/tc-project-service/issues/86#issuecomment-393373319>,
or mute the thread

**Comment by ngoctay** [comment]
For `products`, I have some questions:

```
    {
        id:23,
        productKey:'website_development'
    }
```

1. Will we use this `id` to create new record in phase_products table? I mean that we will set the `phase_products.id` manually instead of using the PK auto-increment. Just wanted to double check because I don't quite understand why we need to set a fixed `id` here because if so, we can't re-use the project_template for creating another project.

2. I don't see `productKey` in the phase_products table.

**Comment by vikasrohit** [comment]
1. No, this id would be used to set `templateId` field of the `phase_products` table. `phase_products.id` would be auto incremented.
2. Yes, right now we are not using productKey field directly in `phase_products` table. This is kept to make the json more human readable and as future possibilities to say only `productKey` in the this json and we would search for the latest version of the `product_template` and set its id in the `templateId` field of the `phase_products` table.

**Comment by vikasrohit** [comment]
Closing as it is done and deployed to prod.
